version: "3.8"

services:
  api-gateway:
    # image: pg/gateway
    build: ./services/gateway
    container_name: pg-gateway
    ports:
      - 2001:80

  webapp:
    # image: pg/ui
    container_name: pg-webapp
    build: ./clients/webapp
    ports:
      - 2000:80

  sudoku:
    # image: pg/sudoku
    build: ./services/sudoku
    container_name: pg-sudoku
    # ports:
    #   - 2003:80

  identity:
    # image: pg/identity
    build: ./services/identity
    container_name: pg-identity
    # ports:
    #   - 2002:80
