version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    container_name: pg-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: pg-mongo-express
    restart: always
    ports:
      - 2100:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  api-gateway:
    # image: pg/gateway
    build: ./services/gateway
    container_name: pg-gateway
    ports:
      - 2001:80

  webapp:
    # image: pg/ui
    container_name: pg-webapp
    build: ./clients/webapp
    ports:
      - 2000:80

  sudoku:
    # image: pg/sudoku1
    build: ./services/sudoku
    container_name: pg-sudoku
    environment:
      MONGO_CONNSTR: mongodb://root:example@mongo:27017/sudoku-db?authSource=admin&readPreference=primary&ssl=false
    # ports:
    #   - 2003:80

  identity:
    # image: pg/identity
    build: ./services/identity
    container_name: pg-identity
    # ports:
    #   - 2002:80
