version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    container_name: pg-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: pg-mongo-express
    restart: always
    ports:
      - 2100:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  prometheus:
    image: prom/prometheus
    container_name: pg-prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: pg-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    restart: always
    ports:
      - 9080:3000

  api-gateway:
    build: ./services/gateway
    container_name: pg-gateway
    ports:
      - 2001:80

  webapp:
    container_name: pg-webapp
    build: ./clients/webapp
    ports:
      - 2000:80

  sudoku:
    build: ./services/sudoku
    container_name: pg-sudoku
    environment:
      MONGO_CONNSTR: mongodb://root:example@mongo:27017/sudoku-db?authSource=admin&readPreference=primary&ssl=false
    # ports:
    #   - 2003:80

  identity:
    build: ./services/identity
    container_name: pg-identity
    # ports:
    #   - 2002:80
