### successfull login
###
POST http://localhost:2001/api/identity/user/login
Content-Type: application/json

{
  "username": "shai",
  "password": "123456"
}

###
GET http://localhost:2001/api/identity/user/profile

###
GET http://localhost:2001/api/identity/user/token

###
POST http://localhost:2001/api/identity/user/logout
